Users:
    type: entity
    table: users
    uniqueConstraints:
        email:
            columns:
                - email
        telephone:
            columns:
                - telephone
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        motDePasse:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: mot_de_passe
        dateNaissance:
            type: date
            nullable: false
            column: date_naissance
        telephone:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
